### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by gmav** [longshine/Mina.NET#13]
Hello i've noticed an issue on my Mina.Net based server, after awhile my server starts receiving data in small chunks instead of the full capacity of the buffer. I've traced the issue down to SocketAsyncEventArgsBuffer, the .Clear() method which is called prior to any receive, has no real effect on Capacity (as it returns _socketAsyncEventArgs.Count) and it may lead to performance degradation.

thanks

geo

**Comment by longshine** [comment]
Hi~ Thanks for reporting this, but I'm not sure if I get your point right or not.

The buffer's <code>Clear()</code> method will NOT change its <code>Capacity</code>, only set <code>Position</code> to 0 and <code>Limit</code> to Capacity, preparing for writing-to-buffer mode.
The <code>Capacity</code> is the maximal count of bytes that can be stored in a buffer. It won't change unless a buffer is expanded or shrinked. Since a <code>SocketAsyncEventArgsBuffer</code> cannot be expanded or shrinked, its <code>Capacity</code> remains the same as the inner <code>_socketAsyncEventArgs.Count</code>.

Besides, the <code>Socket.ReceiveAsync()</code> method use a socketAsyncEventArgs directly, despite of the state of its ownner SocketAsyncEventArgsBuffer, so it should not be affected by the buffer.

I'll check later if there's any other issue.

**Comment by longshine** [comment]
The <code>SocketAsyncEventArgsBuffer</code> adapts a <code>SocketAsyncEventArgs</code> as <code>IoBuffer</code>, but never changes its properties.

**Comment by gmav** [comment]
Hi again longshine, i think SocketAsyncEventArgs.Count remains the same after Clear so the next read operation reads less than expected number of bytes.

**Comment by longshine** [comment]
Hi~
Please note that <code>SocketAsyncEventArgs.Count</code> is a readonly property.
See MSDN (https://msdn.microsoft.com/library/system.net.sockets.socketasynceventargs.count%28v=vs.100%29.aspx).

> Gets the maximum amount of data, in bytes, to send or receive in an asynchronous operation.

> This property is set by calling the SetBuffer method. 

The <code>SocketAsyncEventArgs.Count</code> is always the maximum capacity.
The <code>SocketAsyncEventArgs.BytesTransferred</code> shows how many bytes are actually read or written.

About SocketAsyncEventArgs class please refer to MSDN (https://msdn.microsoft.com/library/system.net.sockets.socketasynceventargs%28v=vs.100%29.aspx).

**Comment by longshine** [comment]
Some other reasons may cause this issue. I suggest switching to .NET 2.0 build to see if this happens again. Mina.NET for .NET 2.0 uses APM instead of SocketAsyncEventArgs, and tries to read full size of buffer with following code:

```csharp
Socket.BeginReceive(_readBuffer, 0, _readBuffer.Length,
    SocketFlags.None, ReceiveCallback, Socket);
```

**Comment by gmav** [comment]
"The SocketAsyncEventArgs.Count is always the maximum capacity."

Just check the output from my server, i just dumped the received bytes inside AsyncSocketSession.ProcessReceive, i use 8192 byte buffers and only one client connected:

Session starting...
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 8192, SocketAsyncEventArgs.Count: 8192
Bytes received: 5109, SocketAsyncEventArgs.Count: 8192
Bytes received: 258, SocketAsyncEventArgs.Count: 8192
Session finished, disconnecting...

Session starting...
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
Bytes received: 42, SocketAsyncEventArgs.Count: 42
(and goes on reading 42 bytes ...)


Actually the problem is solved if you reassign a buffer with _socketAsyncEventArgs.SetBuffer(buffer, 0, buffer.Length);

**Comment by longshine** [comment]
Thanks for your help! I find where the problem is.

It is not the reading buffer but the writing buffer whose buffer size is changed. When a writing buffer is repooled and reused as a reading buffer, its buffer size is not correctly reset to max, remaining the same as the count of last wrting bytes.

I will try to fix this in next commit.

**Comment by longshine** [comment]
Hi geo,

I submitted a commit hoping to solve this issue. Please check it out and see if your problem is solved.
To avoid heavy calls to the <code>SocketAsyncEventArgs.SetBuffer(...)</code> method, I only reset the buffer size when a buffer is being repooled.

**Comment by gmav** [comment]
Hello i run the tests again and i confirm that the issue is gone. Thanks alot!

**Comment by longshine** [comment]
Thanks for your help:)
